biomarketx/backend/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.main, name='main'),
    url(r'^login/$', views.admin_login, name='admin_login'),
    url(r'^logout/$', views.admin_logout, name='admin_logout'),
    url(r'^profile/$', views.admin_profile, name='admin_profile'),
    url(r'^users/$', views.users, name='users'),
    url(r'^index/$', views.admin_index, name='admin_index'),
    url(r'^providers/$', views.labusers, name='labusers'),
    url(r'^buyers/$', views.researchers, name='researchers'),
    url(r'^providers/edit/(?P<l_id>[A-Za-z0-9\w@%._-]+)/$', views.edit_labusers, name='edit_labusers'),
    url(r'^users/edit/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.edit_users, name='edit_users'),
    url(r'^users/del/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.del_users, name='del_users'),
    url(r'^providers/del/(?P<l_id>[A-Za-z0-9\w@%._-]+)/$', views.del_labusers, name='del_labusers'),
    url(r'^buyers/edit/(?P<r_id>[A-Za-z0-9\w@%._-]+)/$', views.edit_researchers, name='edit_researchers'),
    url(r'^buyers/del/(?P<r_id>[A-Za-z0-9\w@%._-]+)/$', views.del_researchers, name='del_researchers'),
    url(r'^services/$', views.admin_services, name='admin_services'),
    url(r'^services/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_subservices, name='admin_subservices'),
    url(r'^service/add/$', views.admin_addservices, name='admin_addservices'),
    url(r'^addservices/$', views.addservices, name='addservices'),
    url(r'^service/edit/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_services_edit, name='admin_services_edit'),
    url(r'^service/del/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_services_del, name='admin_services_del'),
    url(r'^service/(?P<u_id>[A-Za-z0-9\w@%._-]+)/add/$', views.admin_add_subservices, name='admin_add_subservices'),
    url(r'^service/sub/edit/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_subservices_edit, name='admin_subservices_edit'),
    url(r'^service/sub/del/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_subservices_del, name='admin_subservices_del'),
    # url(r'^admin_subservices_two/$', views.admin_subservices_two, name='admin_subservices_two'),
    url(r'^services/(?P<s_id>[A-Za-z0-9\w@%._-]+)/sub/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_subservices_two, name='admin_subservices_two'),
    url(r'^services/(?P<p_id>[A-Za-z0-9\w@%._-]+)/sub/(?P<s_id>[A-Za-z0-9\w@%._-]+)/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_subservices_three, name='admin_subservices_three'),
    url(r'^service/add/(?P<s_id>[A-Za-z0-9\w@%._-]+)/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_add_subservices_two, name='admin_add_subservices_two'),
    url(r'^service/add/(?P<s_id>[A-Za-z0-9\w@%._-]+)/(?P<u_id>[A-Za-z0-9\w@%._-]+)/(?P<p_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_add_subservices_three, name='admin_add_subservices_three'),
    url(r'^service/edition/(?P<s_id>[A-Za-z0-9\w@%._-]+)/(?P<u_id>[A-Za-z0-9\w@%._-]+)$', views.admin_services_two_edit, name='admin_services_two_edit'),
    url(r'^service/editions/(?P<p_id>[A-Za-z0-9\w@%._-]+)/(?P<s_id>[A-Za-z0-9\w@%._-]+)/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_services_three_edit, name='admin_services_three_edit'),


]

biomarketx/biomarketx/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include('biomarketxapp.urls', namespace="bioapp")),
    url(r'^accounts/', include('allauth.urls')),   
    url(r'^backend/', include('backend.urls', namespace="backend")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')), 
    # url(r'^messages/', include('django_messages.urls')),
    url(r'^__alohaeditor__/', include('aloha_editor.urls', namespace='aloha_editor')),

    #url(r'^editor/', include('demo_application.urls')),
    #url(r'^editor$', ckeditor_form_view, name='ckeditor-form'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

biomarketx/biomarketxapp/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.db.models import signals
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone


# Create your models here.
from django.contrib.auth.models import User
User._meta.get_field('email')._unique = True
User._meta.get_field('username')._unique = False
# Create your models here.
class Userroles(models.Model):
    user_id = models.IntegerField()
    role_id = models.IntegerField()
    roll_name=models.CharField(max_length=250)
    status =models.BooleanField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Users(models.Model):
    user_id = models.IntegerField()
    role_id = models.IntegerField()
    fname = models.CharField(max_length=250)
    lname = models.CharField(max_length=250)
    email = models.EmailField(max_length=250)
    phone = models.CharField(max_length=15)
    how_bio = models.CharField(max_length=250,blank=True)
    name_org = models.CharField(max_length=250,blank=True)
    username = models.CharField(max_length=250)
    is_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
      get_latest_by = 'created_at'

class Researcher_more_info(models.Model):
    user_id = models.IntegerField()
    desc=models.TextField()
    publications=models.CharField(max_length=250)
    model_pic = models.ImageField(upload_to = 'pic_folder',null=True, blank=True)

class Researcher_education(models.Model):
    user_id = models.IntegerField()
    institute=models.CharField(max_length=250,blank=True)
    degree=models.CharField(max_length=250,blank=True)
    field_study=models.CharField(max_length=250,blank=True)
    study_start=models.CharField(max_length=250,blank=True)
    study_stop=models.CharField(max_length=250,blank=True)
    study_continue=models.CharField(max_length=250,blank=True)
    notes=models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)    


class Researcher_emplyment(models.Model):
    user_id = models.IntegerField()
    employer=models.CharField(max_length=250,blank=True)
    title=models.CharField(max_length=250,blank=True)
    study_start=models.CharField(max_length=250,blank=True)
    study_stop=models.CharField(max_length=250,blank=True)
    study_continue=models.CharField(max_length=250,blank=True)
    month_start=models.CharField(max_length=250,blank=True)
    month_stop=models.CharField(max_length=250,blank=True)
    notes=models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)    


class Researcher_publications(models.Model):
    user_id = models.IntegerField()
    title=models.CharField(max_length=500,blank=True)
    scientist_name=models.CharField(max_length=250,blank=True)
    used_for=models.CharField(max_length=250,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)    


class Publications(models.Model):
    title=models.CharField(max_length=500,blank=True)
    scientist_name=models.CharField(max_length=250,blank=True)
    used_for=models.CharField(max_length=250,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Services(models.Model):
    pid = models.IntegerField()
    name = models.CharField(max_length=300)    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.BooleanField()
    admin_status = models.BooleanField()

class Lab(models.Model):
    #user = models.ForeignKey(Users)
    user_id = models.IntegerField()
    service_id = models.IntegerField(null=True)
    title = models.CharField(max_length=500,blank=True)
    caption = models.CharField(max_length=250,blank=True)
    orgname =models.CharField(max_length=250,blank=True)
    typeorg=models.CharField(max_length=250,blank=True)
    core_facility = models.CharField(max_length=250,blank=True)
    desc = models.TextField()
    # logo = models.ImageField(null=True, blank=True,upload_to="/media")
    model_pic = models.ImageField(upload_to="images", null=True, blank=True)
    city=models.CharField(max_length=250,blank=True)
    state=models.CharField(max_length=250,blank=True)
    country = models.CharField(max_length=250,blank=True)
    # labservices_id = models.IntegerField()
    # labendorse_id = models.IntegerField()
    # labreviews_id = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class LabServices(models.Model):
    #lab_id = models.ForeignKey(Lab)
    #service_id = models.ForeignKey(Service)
    lab_id = models.IntegerField()
    service_id = models.IntegerField(null=True)
    title = models.CharField(max_length=500,blank=True)
    price = models.FloatField()
    currency = models.CharField(max_length=500,blank=True)
    unit = models.CharField(max_length=500,blank=True)
    desc = models.TextField()
    url=models.CharField(max_length=500,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class LabEndorse(models.Model):
    #lab_id = models.ForeignKey(Lab)
    #service_id = models.ForeignKey(Service)
    lab_id = models.IntegerField()
    desc = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class LabReviews(models.Model):
    #lab_id = models.ForeignKey(Lab)
    #service_id = models.ForeignKey(Service)
    lab_id = models.IntegerField()
    desc = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class LabMembers(models.Model):
    lab = models.ForeignKey(Lab)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Countries(models.Model):
    country_name = models.CharField(max_length=160)
    created_at = models.DateTimeField(auto_now_add=True)

class Notifications(models.Model):
    user_id = models.ForeignKey(Users)
    desc = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Experiment(models.Model):
    user_id = models.ForeignKey(Users)
    lab_id = models.ForeignKey(Lab)
    experiment=models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Lab_type(models.Model):
    user_id = models.ForeignKey(Users)
    lab_id = models.ForeignKey(Lab)
    lab_type=models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Parent_organization(models.Model):
    user_id = models.ForeignKey(Users)
    lab_id = models.ForeignKey(Lab)
    organization=models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class species(models.Model):
    user_id = models.ForeignKey(Users)
    lab_id = models.ForeignKey(Lab)
    species=models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Certifications(models.Model):
    user_id = models.ForeignKey(Users)
    lab_id = models.ForeignKey(Lab)
    certifications=models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Equipment(models.Model):
    user_id = models.ForeignKey(Users)
    lab_id = models.ForeignKey(Lab)
    equipment=models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Reagents(models.Model):
    user_id = models.ForeignKey(Users)
    lab_id = models.ForeignKey(Lab)
    reagents=models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Labphotos(models.Model):
    # user_id = models.IntegerField()
    # lab_id = models.IntegerField()
    photo = models.FileField(upload_to="Lab-photos")


class Profilepic(models.Model):
    user_id=models.IntegerField(null=True)
    model_pic = models.ImageField(upload_to = 'pic_folder/', null=True, blank=True)



class Labkeywords(models.Model):
    lab_keywords=models.TextField(max_length=250)

class Book(models.Model):
    title = models.CharField(max_length=250)
    desc = models.TextField()

class Quotes(models.Model):
    #id=models.IntegerField()#AUTO_INCREMENT
    sid=models.CharField(max_length=250,blank=True)
    researcher_id=models.IntegerField()
    researcher_name=models.CharField(max_length=250,blank=True)
    lab_id=models.IntegerField()
    service_id=models.IntegerField(null=True)
    service_name=models.CharField(max_length=250,blank=True)
    desc=models.TextField()
    notes=models.TextField()
    price=models.FloatField(null=True)
    duration=models.CharField(max_length=250,blank=True)
    memo=models.CharField(max_length=250,blank=True)
    status_id=models.IntegerField()    
    sent_by=models.CharField(max_length=250,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Quotes_msgs(models.Model):
    #id=models.IntegerField()#AUTO_INCREMENT
    quote_id=models.IntegerField()
    body=models.TextField()
    msg_status=models.CharField(max_length=250)#new,trash,sent
    sender_id=models.IntegerField()
    

biomarketx/templates/django_messages/base.html
{% extends "base.html" %}
{% load i18n %}

{% block bodyclass %}about{% endblock %}
{% block content %}  
{% endblock %}
{% block sidebar %}
<ul class="subnavilist">
    <li><a href="{% url 'messages_inbox' %} ">&raquo;&nbsp;{% trans "Inbox" %}</a></li>
    <li><a href="{% url 'messages_outbox' %} ">&raquo;&nbsp;{% trans "Sent Messages" %}</a></li>
    <li><a href="{% url 'messages_compose' %} ">&raquo;&nbsp;{% trans "New Message" %}</a></li>
    <li><a href="{% url 'messages_trash' %} ">&raquo;&nbsp;{% trans "Trash" %}</a></li>
</ul>
{% endblock %}

biomarketx/templates/django_messages/compose.html
{% extends "new_base.html" %} 
{% load i18n %} 
{% block content %} 
<h1>{% trans "Compose Message"%}</h1>


<form action="" method="post">
{% csrf_token %} 
	<table>
		<tr>
			<th><label for="id_recipient">Recipient:</label></th>
			<td><input id="id_recipient" name="recipient" type="text" /></td>
		</tr>
		<tr>
			<th><label for="id_subject">Subject:</label></th>
			<td><input id="id_subject" maxlength="120" name="subject" type="text" /></td>
		</tr>
		<tr>
			<th><label for="id_body">Body:</label></th>
			<td><textarea cols="55" id="id_body" name="body" rows="12"></textarea></td>
		</tr>
	</table>
	<input type="submit" value="{% trans "Send" %} &raquo;"/>
</form>




{% endblock %}

biomarketx/templates/django_messages/inbox.html
{% extends "new_base.html" %} 
{% load i18n %} 


{% block content %}
<h1>{% trans "Inbox" %}</h1>
{% if message_list %} 
<table class="messages">
    <thead>
        <tr><th>{% trans "Sender" %}</th><th>{% trans "Subject" %}</th><th>{% trans "Received" %}</th><th>{% trans "Action" %}</th></tr>
    </thead>
    <tbody>
{% for message in message_list %} 
    <tr>
        <td>{{ message.sender }}</td>
        <td>
            {% if message.new %}<strong>{% endif %}
            {% if message.replied %}<em>{% endif %}
            <a href="{{message.get_absolute_url }}">{{ message.subject }}</a>
            {% if message.replied %}</em>{% endif %}
            {% if message.new %}</strong>{% endif %}</td>
        <td>{{ message.sent_at|date:_("DATETIME_FORMAT") }}</td>
        <td><a href="{% url 'messages_delete' message.id %}">{% trans "delete" %}</a></td>
    </tr>
{% endfor %}
    </tbody>
</table>
{% else %}
<p>{% trans "No messages." %}</p>
{% endif %}  
{% endblock %}

biomarketx/templates/django_messages/new_message.html
{% load i18n %}
{% load url from future %}

{% blocktrans with recipient=message.recipient sender=message.sender %}Hello {{ recipient }},

you received a private message from {{ sender }} with
the following contents:{% endblocktrans %}

{{ message.body|safe }}

--
{% blocktrans %}Sent from {{ site_url }}{% endblocktrans %}
{% trans "Inbox" %}: {{ site_url }}{% url 'messages_inbox' %}
{% trans "Reply" %}: {{ site_url }}{% url 'messages_reply' message.pk %}     

biomarketx/templates/django_messages/outbox.html
{% extends "django_messages/base.html" %} 
{% load i18n %} 
{% load url from future %}

{% block content %} 
<h1>{% trans "Sent Messages" %}</h1>
{% if message_list %} 
<table class="messages"> 
    <thead>
        <tr><th>{% trans "Recipient" %}</th><th>{% trans "Subject" %}</th><th>{% trans "Sent" %}</th><th>{% trans "Action" %}</th></tr>
    </thead>
    <tbody>
{% for message in message_list %} 
    <tr>
        <td>{{ message.recipient }}</td>
        <td>
        <a href="{{ message.get_absolute_url }}">{{ message.subject }}</a>
        </td>
        <td>{{ message.sent_at|date:_("DATETIME_FORMAT") }}</td>
        <td><a href="{% url 'messages_delete' message.id %}?next={% url 'messages_outbox' %}">{% trans "delete" %}</a></td>
    </tr>
{% endfor %}
    </tbody>
</table>
{% else %}
<p>{% trans "No messages." %}</p>
{% endif %}   
{% endblock %}

biomarketx/templates/django_messages/trash.html
{% extends "django_messages/base.html" %} 
{% load i18n %} 
{% load url from future %}

{% block content %} 
<h1>{% trans "Deleted Messages" %}</h1>
{% if message_list %} 
<table class="messages">
    <thead>
        <tr><th>{% trans "Sender" %}</th><th>{% trans "Subject" %}</th><th>{% trans "Date" %}</th><th>{% trans "Action" %}</th></tr>
    </thead>
    <tbody>
{% for message in message_list %} 
    <tr>
        <td>{{ message.sender }}</td>
        <td> 
        {{ message.subject }}
        </td>
        <td>{{ message.sent_at|date:_("DATETIME_FORMAT") }}</td>
        <td><a href="{% url 'messages_undelete' message.id %}">{% trans "undelete" %}</a></td>
    </tr>
{% endfor %}
    </tbody>
</table>
{% else %}
<p>{% trans "No messages." %}</p>
{% endif %}   
<br />
<p>{% trans "Deleted Messages are removed from the trash at unregular intervals, don't rely on this feature for long-time storage." %}</p>
{% endblock %}

biomarketx/templates/django_messages/view.html
{% extends "django_messages/base.html" %}
{% load i18n %}
{% load url from future %}

{% block content %}
<h1>{% trans "View Message" %}</h1>
<dl class="message-headers">
    <dt>{% trans "Subject" %}</dt>
    <dd><strong>{{ message.subject }}</strong></dd>
    <dt>{% trans "Sender" %}</dt>
    <dd>{{ message.sender }}</dd>
    <dt>{% trans "Date" %} </dt>
    <dd>{{ message.sent_at|date:_("DATETIME_FORMAT")}}</dd>
    <dt>{% trans "Recipient" %}</dt>
    <dd>{{ message.recipient }}</dd>
</dl>
{{ message.body|linebreaksbr }}<br /><br />

{% ifequal message.recipient.pk user.pk %}
<a href="{% url 'messages_reply' message.id %}">{% trans "Reply" %}</a>
{% endifequal %}
<a href="{% url 'messages_delete' message.id %}">{% trans "Delete" %}</a>

{% comment %}Example reply_form integration
{% if reply_form %}
<h1>{% trans "Compose reply"%}</h1>
<form action="{% url 'messages_reply' message.id %}" method="post">
{% csrf_token %}
<table>
{{ reply_form.as_table }}
</table>
<input type="submit" value="{% trans "Send" %} &raquo;"/>
</form>
{% endif %}
{% endcomment %}
{% endblock %}