biomarketx/backend/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.main, name='main'),
    url(r'^login/$', views.admin_login, name='admin_login'),
    url(r'^logout/$', views.admin_logout, name='admin_logout'),
    url(r'^profile/$', views.admin_profile, name='admin_profile'),
    url(r'^users/$', views.users, name='users'),
    url(r'^index/$', views.admin_index, name='admin_index'),
    url(r'^providers/$', views.labusers, name='labusers'),
    url(r'^buyers/$', views.researchers, name='researchers'),
    url(r'^providers/edit/(?P<l_id>[A-Za-z0-9\w@%._-]+)/$', views.edit_labusers, name='edit_labusers'),
    url(r'^users/edit/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.edit_users, name='edit_users'),
    url(r'^users/del/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.del_users, name='del_users'),
    url(r'^providers/del/(?P<l_id>[A-Za-z0-9\w@%._-]+)/$', views.del_labusers, name='del_labusers'),
    url(r'^buyers/edit/(?P<r_id>[A-Za-z0-9\w@%._-]+)/$', views.edit_researchers, name='edit_researchers'),
    url(r'^buyers/del/(?P<r_id>[A-Za-z0-9\w@%._-]+)/$', views.del_researchers, name='del_researchers'),
    url(r'^services/$', views.admin_services, name='admin_services'),
    url(r'^services/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_subservices, name='admin_subservices'),
    url(r'^service/add/$', views.admin_addservices, name='admin_addservices'),
    url(r'^addservices/$', views.addservices, name='addservices'),
    url(r'^service/edit/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_services_edit, name='admin_services_edit'),
    url(r'^service/del/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_services_del, name='admin_services_del'),
    url(r'^service/(?P<u_id>[A-Za-z0-9\w@%._-]+)/add/$', views.admin_add_subservices, name='admin_add_subservices'),
    url(r'^service/sub/edit/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_subservices_edit, name='admin_subservices_edit'),
    url(r'^service/sub/del/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_subservices_del, name='admin_subservices_del'),
    # url(r'^admin_subservices_two/$', views.admin_subservices_two, name='admin_subservices_two'),
    url(r'^services/(?P<s_id>[A-Za-z0-9\w@%._-]+)/sub/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_subservices_two, name='admin_subservices_two'),
    url(r'^services/(?P<p_id>[A-Za-z0-9\w@%._-]+)/sub/(?P<s_id>[A-Za-z0-9\w@%._-]+)/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_subservices_three, name='admin_subservices_three'),
    url(r'^service/add/(?P<s_id>[A-Za-z0-9\w@%._-]+)/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_add_subservices_two, name='admin_add_subservices_two'),
    url(r'^service/add/(?P<s_id>[A-Za-z0-9\w@%._-]+)/(?P<u_id>[A-Za-z0-9\w@%._-]+)/(?P<p_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_add_subservices_three, name='admin_add_subservices_three'),
    url(r'^service/edition/(?P<s_id>[A-Za-z0-9\w@%._-]+)/(?P<u_id>[A-Za-z0-9\w@%._-]+)$', views.admin_services_two_edit, name='admin_services_two_edit'),
    url(r'^service/editions/(?P<p_id>[A-Za-z0-9\w@%._-]+)/(?P<s_id>[A-Za-z0-9\w@%._-]+)/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_services_three_edit, name='admin_services_three_edit'),


]

biomarketx/biomarketx/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include('biomarketxapp.urls', namespace="bioapp")),
    url(r'^accounts/', include('allauth.urls')),   
    url(r'^backend/', include('backend.urls', namespace="backend")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')), 
    # url(r'^messages/', include('django_messages.urls')),
    url(r'^__alohaeditor__/', include('aloha_editor.urls', namespace='aloha_editor')),

    #url(r'^editor/', include('demo_application.urls')),
    #url(r'^editor$', ckeditor_form_view, name='ckeditor-form'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

biomarketx/biomarketxapp/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

	url(r'^$', views.index, name='index'),    
    url(r'^signup/$',views.signup_select, name='signup'),
    url(r'^signup/buyer/$',views.signup_researcher, name='signup_researcher'),
    url(r'^signup/provider/$',views.signup_lab, name='signup_lab'),
    url(r'^login/$',views.login, name='login'),
    url(r'^logout/$',views.logout_page, name='logout'),
    url(r'^about/$',views.about, name='about'),
    url(r'^consulting/$',views.new_consulting, name='new_consulting'),
    url(r'^support/$',views.new_contactus, name='support'),
    url(r'^services/(?P<ser_name>[A-Za-z0-9\w @%&._-]+)/$', views.show_services,name='show_services'),
    url(r'^services/sub/(?P<p_id>[A-Za-z0-9\w @%&._-]+)/$',views.new_services_inner, name='new_services_inner'),        
    url(r'^projects/$',views.new_projects, name='new_projects'),
    url(r'^edit-profile/$',views.editprofile, name='editprofile'),   
    url(r'^lab-services/$',views.lab_services, name='show_lab'),
    url(r'^lab-reviews/$',views.lab_reviews, name='lab_reviews'),
    url(r'^lab-endorse/$',views.lab_endorse, name='lab_endorse'),
    url(r'^show-your-lab/$',views.show_your_lab, name='show_your_lab'),    
    url(r'^list-your-lab/$',views.list_your_lab,name='list_your_lab'),
    url(r'^lab-profile-page/$',views.lab_profile_page,name='lab_profile_page'),    
    url(r'^edit-provider-profile/$',views.edit_lab_profile,name='edit_lab_profile'),
    # url(r'^edit-provider-services/(?P<lab_service_id>[A-Za-z0-9\w@%._-]+)/$',views.edit_lab_services,name='edit_lab_services'),
    url(r'^provider/lab-service/del/(?P<lab_service_id>[A-Za-z0-9\w@%._-]+)/$',views.del_lab_service,name='del_lab_service'),
    url(r'^provider/provider-service/edit/(?P<lab_service_id>[A-Za-z0-9\w@%._-]+)/$',views.edit_provider_service,name='edit_provider_service'),
    url(r'^lab-photos/$',views.upload_labphotos,name='upload_labphotos'),
    url(r'^upload-pic/$',views.upload_pic,name='upload_pic'),    
    url(r'^upload/profile-pic/$', views.upload_profile_pic,name='upload_profile_pic'),
    url(r'^login1/$',views.image_upload, name='login1'),
    url(r'^lab_list_all/$',views.lab_list_all, name='lab_list_all'),
    url(r'^autocomplete/$', views.searching_labs,name='autocomplete'),
    url(r'^search/$', views.search_result,name='search_result'),
    url(r'^search_keywords/$', views.search_keywords,name='search_keywords'),
    url(r'^searching/$', views.dynamic_searching,name='dynamic_searching'),
    url(r'^demo_publications/$', views. demo_publications,name=' demo_publications'),   
    url(r'^dashboard/$', views.dashboard,name='dashboard'),
    url(r'^search_filters/$', views.search_filters,name='search_filters'),
    url(r'^store-font/(?P<store_id>[0-9]+)/$', views.store_front,name='store_front'),    
    url(r'^parent-services$', views.add_parentservices,name='add_parentservices'),  
    url(r'^book$', views.book_detail,name='book_detail'),  
    url(r'^sample$', views.sample,name='sample'),
    
    url(r'^provider/$', views.labdashboard,name='labdashboard'),
    url(r'^provider/profile/$', views.new_lab_profile,name='new_lab_profile'),
    url(r'^provider/quotes/$', views.new_lab_quotes,name='new_lab_quotes'),
    url(r'^provider/messages/$', views.new_lab_messages,name='new_lab_messages'),
    url(r'^provider/desc/(?P<id>[0-9]+)$', views.view_quote,name='view_quote'),
    url(r'^provider-quote/(?P<qut_id>[0-9]+)/$', views.lab_send_quote,name='lab_send_quote'),
    url(r'^provider/orders/$', views.provider_orders,name='provider_orders'),
    url(r'^provider/order/(?P<ordr_id>[0-9]+)$', views.privider_order_desc,name='provider_order_desc'),
    
    url(r'^buyer/$',views.researcher_profile_page,name='researcher_profile_page'),    
    url(r'^buyer/quotes/$', views.new_res_quotes,name='new_res_quotes'),
    url(r'^buyer/desc/(?P<id>[0-9]+)$', views.res_view_quote,name='res_view_quote'),
    
    url(r'^buyer/edit/basics/$',views.edit_researcher_profile,name='edit_researcher_profile'),
    url(r'^buyer/edit/password/$',views.edit_researcher_password,name='edit_researcher_password'),
    url(r'^buyer/edit/education$',views.researcher_education,name='researcher_education'),
    url(r'^buyer/edit/education/add$',views.add_degree,name='add_degree'),
    url(r'^buyer/edit/education/edit/(?P<degree_id>[0-9]+)/$', views.edit_add_degree,name='edit_add_degree'),
    url(r'^buyer/edit/education/delete/(?P<degree_id>[0-9]+)/$', views.delete_degree,name='delete_degree'),
    url(r'^buyer/edit/publications/$', views.publications,name='add_publications'),
    url(r'^buyer/edit/publications/add$', views.add_publications,name='adding_pub'),
    url(r'^buyer/edit/publications/search$', views.search_publications,name='search_publications'),    
    url(r'^buyer/edit/publications/add/(?P<degree_id>[0-9]+)/$', views.store_publications,name='store_publications'),
    url(r'^buyer/edit/employment/$', views.researcher_employment,name='researcher_employment'),
    url(r'^buyer/edit/employment/add$', views.researcher_add_employment,name='researcher_add_employment'),
    url(r'^buyer/edit/employment/add/(?P<emp_id>[0-9]+)/$', views.edit_add_employment,name='edit_add_employment'),
    url(r'^buyer/edit/employment/delete/(?P<emp_id>[0-9]+)/$', views.delete_employment,name='delete_employment'),
    url(r'^buyer/edit/publications/delete/(?P<emp_id>[0-9]+)/$', views.delete_publications,name='delete_publications'),
    url(r'^buyer/orders/$', views.buyer_orders,name='buyer_orders'),
    url(r'^buyer/order/(?P<ordr_id>[0-9]+)$', views.buyer_order_desc,name='buyer_order_desc'),

    url(r'^send-quote/(?P<serv_id>[0-9]+)/(?P<lab_id>[0-9]+)/$', views.send_quote,name='send_quote'),   
    url(r'^multi-quote/(?P<serv_id>[0-9]+)/$', views.multiquote,name='multiquote'),
    url(r'^multiquote-res/(?P<serv_id>[0-9]+)/$', views.Multiquote_researcher,name='Multiquote_researcher'),    
    url(r'^quote-filter/$', views.quote_status_filter,name='quote_status_filter'),
    
    url(r'^send-quote/thanks/$', views.send_quote_thanks,name='send_quote_thanks'),
    url(r'^service-filters/$', views.service_filters,name='service_filters'),
    url(r'^breadcroomb/$', views.breadcroomb,name='breadcroomb'),

    url(r'^messages/$', views.allmessages, name='allmessages'),
    url(r'^buyer/messages/compose/$', views.compose, name='messages_compose'),
    url(r'^buyer/messages/inbox/$', views.inbox, name='messages_inbox'),
    url(r'^buyer/messages/sent/$', views.outbox, name='messages_outbox'),
    url(r'^buyer/messages/view/(?P<msg_id>[0-9]+)/$', views.buyer_msg_view, name='messages_view'),
    url(r'^buyer/messages/reply/(?P<msg_id>[0-9]+)/$', views.reply, name='messages_reply'),
    url(r'^buyer/messages/trash/$', views.trash, name='messages_trash'),
    url(r'^buyer/messages/trash-box/$', views.trash_messages, name='trash_messages'),
    url(r'^buyer/messages/trash-inbox/$', views.trash_move_inbox, name='trash_move_inbox'),
    url(r'^buyer/messages/trash-delete/$', views.trash_delete, name='trash_delete'),

    url(r'^compose/$', views.messages_compose, name='messages1_compose'),
    url(r'^provider-compose/$', views.provider_messages_compose, name='provider_messages_compose'),

    url(r'^provider/messages/compose/$', views.provider_compose, name='provider_messages_compose'),
    url(r'^provider/messages/inbox/$', views.provider_inbox, name='provider_messages_inbox'),
    url(r'^provider/messages/sent/$', views.provider_outbox, name='provider_messages_outbox'),
    url(r'^provider/messages/view/(?P<msg_id>[0-9]+)/$', views.provider_msg_view, name='provider_msg_view'),
    url(r'^provider/messages/reply/(?P<msg_id>[0-9]+)/$', views.provider_reply, name='provider_messages_reply'),
    url(r'^provider/messages/trash/$', views.provider_trash, name='provider_messages_trash'),
    url(r'^provider/messages/inbox-trash/$', views.move_inbox_trash_provider, name='move_inbox_trash_provider'),
    url(r'^provider/messages/trash-inbox/$', views.trash_move_inbox_provider, name='trash_move_inbox_provider'),
    url(r'^provider/messages/trash-delete/$', views.trash_delete_provider, name='trash_delete_provider'),
    url(r'^provider/messages/sent-trash/$', views.sent_box_provider, name='sent_box_provider'),

    
    url(r'^sort-by-value/$', views.sort_by_value,name='sort_by_value'),    
    url(r'^quote-accept/(?P<qut_id>[0-9]+)/$', views.Quote_accept,name='Quote_accept'),
     url(r'^buyer/quote-reject/(?P<qut_id>[0-9]+)/$', views.Quote_reject,name='Quote_reject'),
    url(r'^testing/$', views.testing, name='testing'),
    url(r'^lab-search-filters/$', views.lab_serch_filters, name='lab_serch_filters'),
    url(r'^proceed-payment/$', views.quote_payment_form, name='quote_payment_form'),
    url(r'^buyer/quote-accept/creditcard/(?P<qut_id>[0-9]+)/$', views.buyer_quote_accept_creditcard, name='buyer_quote_accept_creditcard'),
    url(r'^buyer/payment-type/(?P<qut_id>[0-9]+)/$', views.select_payment_type, name='select_payment_type'),
    url(r'^buyer/quote-accept/wiretransfer/(?P<qut_id>[0-9]+)/$', views.wiretransfer_payment, name='wiretransfer_payment'),
    url(r'^buyer/workroom/(?P<ordr_id>[0-9]+)/$', views.workroom_allocation,name='workroom_allocation'),    
    url(r'^provider/workroom/(?P<ordr_id>[0-9]+)/$', views.provider_workroom,name='provider_workroom'),    


    url(r'^edit/$', views.admin_edit_static, name='admin_edit_static'),
    url(r'^edit1/$', views.admin_edit_staticdata_display,name='admin_edit_staticdata_display'),
    url(r'^staticpage/$', views.admin_staticdata, name='admin_staticdata'),
    url(r'^about_static/$', views.about_static, name='about_static'),

    url(r'^edit_consult/$', views.consulting_edit, name='consulting_edit'),
    url(r'^consult_static/$', views.consulting_static, name='consulting_static'),

    url(r'^projects_edit/$', views.projects_edit, name='projects_edit'),

biomarketx/templates/messages/messages_inbox.html
{% extends "researcher/dash_index.html" %}
{% load staticfiles %}
{% load i18n %}
{% block content %}	

		<section role="main" class="content-body">

					<!-- start: page -->
					<section class="content-with-menu mailbox">
						<div class="content-with-menu-container" data-mailbox data-mailbox-view="folder">
							<div class="inner-menu-toggle">
								<a href="#" class="inner-menu-expand" data-open="inner-menu">
									Show Menu <i class="fa fa-chevron-right"></i>
								</a>
							</div>
							
							<menu id="content-menu" class="inner-menu" role="menu">
								{% include 'messages/messages-menu.html' %}
							</menu>
							
						<!-- Inbox -->
							<div class="inner-body mailbox-folder">
								<!-- START: .mailbox-header -->
								<header class="mailbox-header">
									
									<div class="row">
										<div class="col-sm-6">
											<h1 class="mailbox-title text-weight-light m-none">
												<a id="mailboxToggleSidebar" class="sidebar-toggle-btn trigger-toggle-sidebar">
													<span class="line"></span>
													<span class="line"></span>
													<span class="line"></span>
													<span class="line line-angle1"></span>
													<span class="line line-angle2"></span>
												</a>
							
												Inbox
											</h1>
											{% include "messages.html" %}
										</div>
										<div class="col-sm-6">
											<div class="search">
												<div class="input-group input-search">
													<input type="text" class="form-control" name="q" id="q" placeholder="Search...">
													<span class="input-group-btn">
														<button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
													</span>
												</div>
											</div>
										</div>
									</div>
							
								</header>
								
								<!-- END: .mailbox-header -->
							
								<!-- START: .mailbox-actions -->
								<div class="mailbox-actions" >
									<ul class="list-unstyled m-none pt-lg pb-lg">
										<li class="ib mr-sm">
											<!-- <div class="btn-group">
												<a href="#" class="item-action fa fa-chevron-down dropdown-toggle" data-toggle="dropdown"></a>
							
												<ul class="dropdown-menu" role="menu">
													<li><a href="#">All</a></li>
													<li><a href="#">None</a></li>
													<li><a href="#">Read</a></li>
													<li><a href="#">Unread</a></li>
													<li><a href="#">Starred</a></li>
													<li><a href="#">Unstarred</a></li>
												</ul>
											</div> -->
										</li>
										<!-- <li class="ib mr-sm">
											<a class="item-action fa fa-refresh" href="#"></a>
										</li>
										<li class="ib mr-sm">
											<a class="item-action fa fa-tag" href="#"></a>
										</li> -->
										<li class="ib">
											<a class="item-action glyphicon glyphicon-trash" href="#" style="text-decoration:none;color:rgba(210, 70, 45, 0.95);" title="Delete" id="Trashbox"></a>
										</li>
									</ul>
								</div>
								<!-- END: .mailbox-actions -->
							

							
								<div id="mailbox-email-list" class="mailbox-email-list" >
									<div class="nano">
										<div class="nano-content">


										{% if conformation_researcher %}
										


											{% for message in message_list %}
											<ul id="" class="list-unstyled">
											

												<li class="unread">
													<a href="#">
														<div class="col-sender">
															<div class="checkbox-custom checkbox-text-primary ib">
																<input type="checkbox" id="mail1" value="{{message.id}}" name="msgID">
																<label for="mail1"></label>
															</div>
															<p class="m-none ib"><a href="{% url 'bioapp:messages_view' msg_id=message.id %}">{{ message.sender }}</a>
															</p>
														</div>
														<div class="col-mail">

															<p class="m-none mail-content">
																<span class="subject"><a href="{% url 'bioapp:messages_view' msg_id=message.id %}">{{ message.subject }}</a></span>
																<!-- <span class="mail-partial">We are proud to announce that our new theme Porto Admin is ready, wants to know more about it?</span> -->
															</p>
															<p class="m-none mail-date">{{ message.sent_at|date:"SHORT_DATE_FORMAT"}}</p>

														</div>
													</a>
												</li>
											{% endfor %}



										{% elif conformation_lab %}
										


											{% for message1 in provider_message_list %}
											<ul id="" class="list-unstyled">
											

												<li class="unread">
													<a href="#">
														<div class="col-sender">
															<div class="checkbox-custom checkbox-text-primary ib">
																<input type="checkbox" id="mail1">
																<label for="mail1"></label>
															</div>
															<p class="m-none ib">{{ message1.sender }}</p>
														</div>
														<div class="col-mail">
															<p class="m-none mail-content">
																<span class="subject">{{ message1.subject }}</span>
																<!-- <span class="mail-partial">We are proud to announce that our new theme Porto Admin is ready, wants to know more about it?</span> -->
															</p>
															<p class="m-none mail-date">{{ message1.sent_at|date:"SHORT_DATE_FORMAT"}}</p>
														</div>
													</a>
												</li>
											{% endfor %}

										{% else %}
										{%endif%}

										
												<!-- <li>
													<a href="mailbox-email.html">
														<i class="mail-label" style="border-color: #EA4C89"></i>
							
														<div class="col-sender">
															<div class="checkbox-custom checkbox-text-primary ib">
																<input type="checkbox" id="mail2">
																<label for="mail2"></label>
															</div>
															<p class="m-none ib">Okler Themes</p>
														</div>
														<div class="col-mail">
															<p class="m-none mail-content">
																<span class="subject">Porto Admin theme! &nbsp;–&nbsp;</span>
																<span class="mail-partial">Check it out.</span>
															</p>
															<i class="mail-attachment fa fa-paperclip"></i>
															<p class="m-none mail-date">3:35 pm</p>
														</div>
													</a>
												</li> -->
							
												
							
											</ul>
										</div>
									</div>
								</div>
							
							</div>


						<!-- Inbox -->


						</div>
					</section>
					<!-- end: page -->
		</section>



{% endblock %}

biomarketx/templates/messages/messages_view.html
{% extends "researcher/dash_index.html" %}
{% load staticfiles %}
{% load i18n %}
{% block content %}	

		<section role="main" class="content-body">
					<!-- <header class="page-header">
						<h2>E-Mail</h2>
					
						<div class="right-wrapper pull-right">
							<ol class="breadcrumbs">
								<li>
									<a href="index.html">
										<i class="fa fa-home"></i>
									</a>
								</li>
								<li><span>Mailbox</span></li>
								<li><a href="mailbox-folder.html">Inbox</a></li>
								<li><span>E-Mail</span></li>
							</ol>
					
							<a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
						</div>
					</header>
 -->
					<!-- start: page -->
					<section class="content-with-menu mailbox">
						<div class="content-with-menu-container" data-mailbox data-mailbox-view="email">
							<div class="inner-menu-toggle">
								<a href="#" class="inner-menu-expand" data-open="inner-menu">
									Show Menu <i class="fa fa-chevron-right"></i>
								</a>
							</div>
							
							<menu id="content-menu" class="inner-menu" role="menu">		
								{% include 'messages/messages-menu.html' %}						
							</menu>
							<div class="inner-body mailbox-email">
								<div class="mailbox-email-header mb-lg">
									<h3 class="mailbox-email-subject m-none text-weight-light">
										Back to Inbox
									</h3>
							
									<p class="mt-lg mb-none text-md">From <a href="#">{{ message.sender }}</a> to <a href="#">You</a></p>
								</div>
								<div class="mailbox-email-container">
									<div class="mailbox-email-screen">
										<div class="panel">
											<div class="panel-heading">
												<div class="panel-actions">
													<a href="#" class="panel-action panel-action-toggle" data-panel-toggle></a>
													<a href="{% url 'bioapp:messages_reply' msg_id=message.id %}" class="fa fa-mail-reply" name="reply" title="Reply"></a>
													<a href="#" class="fa fa-mail-reply-all" name="reply-all"></a>
													<a href="#" class="fa fa-star-o"></a>
												</div>
							
												<p class="panel-title">{{ message.sender }}<i class="fa fa-angle-right fa-fw"></i> You</p>
											</div>
											<div class="panel-body">	
												<p>{{message.subject}}</p>
												<p>{{message.body}}</p>
											</div>
											<div class="panel-footer">
												<!-- <p class="m-none"><small>July 07, 2014. 9:51pm</small></p> -->
												<p class="m-none"><small>{{ message.sent_at}}</small></p>
												
											</div>
										</div>
							
										<!-- <div class="panel">
											<div class="panel-heading">
												<div class="panel-actions">
													<a href="#" class="panel-action panel-action-toggle" data-panel-toggle></a>
													<a href="#" class="fa fa-mail-reply"></a>
													<a href="#" class="fa fa-mail-reply-all"></a>
													<a href="#" class="fa fa-star-o"></a>
												</div>
							
												<p class="panel-title">You <i class="fa fa-angle-right fa-fw"></i> Okler Themes
											</div>
											<div class="panel-body">
												<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer volutpat nulla et sollicitudin volutpat. Suspendisse consequat massa et varius tincidunt. In quis velit et enim posuere consectetur at et erat. Praesent condimentum ipsum non ligula tempor cursus. Maecenas ornare vitae nibh blandit suscipit. Nulla suscipit mollis dui vitae porttitor. Nulla faucibus neque leo. Sed tincidunt enim sit amet tellus bibendum consectetur. Nunc lobortis metus posuere adipiscing auctor. Duis ante ipsum, malesuada eu risus vitae, mattis dapibus arcu. Nullam metus dui, fermentum dictum nulla id, gravida dignissim eros.</p>							
												
											</div>
											<div class="panel-footer">
												<p class="m-none"><small>July 06, 2014. 03:26pm</small></p>
											</div>
										</div>
							
										<div class="panel">
											<div class="panel-heading">
												<div class="panel-actions">
													<a href="#" class="panel-action panel-action-toggle" data-panel-toggle></a>
													<a href="#" class="fa fa-mail-reply"></a>
													<a href="#" class="fa fa-mail-reply-all"></a>
													<a href="#" class="fa fa-star-o"></a>
												</div>
							
												<p class="panel-title">Okler Themes <i class="fa fa-angle-right fa-fw"></i> You
											</div>
											<div class="panel-body">
												<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer volutpat nulla et sollicitudin volutpat. Suspendisse consequat massa et varius tincidunt. In quis velit et enim posuere consectetur at et erat. Praesent condimentum ipsum non ligula tempor cursus. Maecenas ornare vitae nibh blandit suscipit. Nulla suscipit mollis dui vitae porttitor. Nulla faucibus neque leo. Sed tincidunt enim sit amet tellus bibendum consectetur. Nunc lobortis metus posuere adipiscing auctor. Duis ante ipsum, malesuada eu risus vitae, mattis dapibus arcu. Nullam metus dui, fermentum dictum nulla id, gravida dignissim eros.</p>
							
												
											</div>
											<div class="panel-footer">
												<p class="m-none"><small>July 05, 2014. 10:03am</small></p>
											</div>
										</div> -->
									</div>
							
									<!-- <div class="compose">
										<div id="compose-field" class="compose">
										</div>
										<div class="text-right mt-md">
											<a href="#" class="btn btn-primary">
												<i class="fa fa-send mr-xs"></i>
												Send
											</a>
										</div>
									</div> -->
								</div>
							</div>
						</div>
					</section>
					<!-- end: page -->
				</section>




{% endblock %}