biomarketx/backend/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.main, name='main'),
    url(r'^login/$', views.admin_login, name='admin_login'),
    url(r'^logout/$', views.admin_logout, name='admin_logout'),
    url(r'^profile/$', views.admin_profile, name='admin_profile'),
    url(r'^users/$', views.users, name='users'),
    url(r'^index/$', views.admin_index, name='admin_index'),
    url(r'^providers/$', views.labusers, name='labusers'),
    url(r'^buyers/$', views.researchers, name='researchers'),
    url(r'^providers/edit/(?P<l_id>[A-Za-z0-9\w@%._-]+)/$', views.edit_labusers, name='edit_labusers'),
    url(r'^users/edit/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.edit_users, name='edit_users'),
    url(r'^users/del/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.del_users, name='del_users'),
    url(r'^providers/del/(?P<l_id>[A-Za-z0-9\w@%._-]+)/$', views.del_labusers, name='del_labusers'),
    url(r'^buyers/edit/(?P<r_id>[A-Za-z0-9\w@%._-]+)/$', views.edit_researchers, name='edit_researchers'),
    url(r'^buyers/del/(?P<r_id>[A-Za-z0-9\w@%._-]+)/$', views.del_researchers, name='del_researchers'),
    url(r'^services/$', views.admin_services, name='admin_services'),
    url(r'^services/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_subservices, name='admin_subservices'),
    url(r'^service/add/$', views.admin_addservices, name='admin_addservices'),
    url(r'^addservices/$', views.addservices, name='addservices'),
    url(r'^service/edit/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_services_edit, name='admin_services_edit'),
    url(r'^service/del/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_services_del, name='admin_services_del'),
    url(r'^service/(?P<u_id>[A-Za-z0-9\w@%._-]+)/add/$', views.admin_add_subservices, name='admin_add_subservices'),
    url(r'^service/sub/edit/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_subservices_edit, name='admin_subservices_edit'),
    url(r'^service/sub/del/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_subservices_del, name='admin_subservices_del'),
    # url(r'^admin_subservices_two/$', views.admin_subservices_two, name='admin_subservices_two'),
    url(r'^services/(?P<s_id>[A-Za-z0-9\w@%._-]+)/sub/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_subservices_two, name='admin_subservices_two'),
    url(r'^services/(?P<p_id>[A-Za-z0-9\w@%._-]+)/sub/(?P<s_id>[A-Za-z0-9\w@%._-]+)/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_subservices_three, name='admin_subservices_three'),
    url(r'^service/add/(?P<s_id>[A-Za-z0-9\w@%._-]+)/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_add_subservices_two, name='admin_add_subservices_two'),
    url(r'^service/add/(?P<s_id>[A-Za-z0-9\w@%._-]+)/(?P<u_id>[A-Za-z0-9\w@%._-]+)/(?P<p_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_add_subservices_three, name='admin_add_subservices_three'),
    url(r'^service/edition/(?P<s_id>[A-Za-z0-9\w@%._-]+)/(?P<u_id>[A-Za-z0-9\w@%._-]+)$', views.admin_services_two_edit, name='admin_services_two_edit'),
    url(r'^service/editions/(?P<p_id>[A-Za-z0-9\w@%._-]+)/(?P<s_id>[A-Za-z0-9\w@%._-]+)/(?P<u_id>[A-Za-z0-9\w@%._-]+)/$', views.admin_services_three_edit, name='admin_services_three_edit'),


]

biomarketx/biomarketx/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include('biomarketxapp.urls', namespace="bioapp")),
    url(r'^accounts/', include('allauth.urls')),   
    url(r'^backend/', include('backend.urls', namespace="backend")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')), 
    # url(r'^messages/', include('django_messages.urls')),
    url(r'^__alohaeditor__/', include('aloha_editor.urls', namespace='aloha_editor')),

    #url(r'^editor/', include('demo_application.urls')),
    #url(r'^editor$', ckeditor_form_view, name='ckeditor-form'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

biomarketx/biomarketxapp/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

	url(r'^$', views.index, name='index'),    
    url(r'^signup/$',views.signup_select, name='signup'),
    url(r'^signup/buyer/$',views.signup_researcher, name='signup_researcher'),
    url(r'^signup/provider/$',views.signup_lab, name='signup_lab'),
    url(r'^login/$',views.login, name='login'),
    url(r'^logout/$',views.logout_page, name='logout'),
    url(r'^about/$',views.about, name='about'),
    url(r'^consulting/$',views.new_consulting, name='new_consulting'),
    url(r'^support/$',views.new_contactus, name='support'),
    url(r'^services/(?P<ser_name>[A-Za-z0-9\w @%&._-]+)/$', views.show_services,name='show_services'),
    url(r'^services/sub/(?P<p_id>[A-Za-z0-9\w @%&._-]+)/$',views.new_services_inner, name='new_services_inner'),        
    url(r'^projects/$',views.new_projects, name='new_projects'),
    url(r'^edit-profile/$',views.editprofile, name='editprofile'),   
    url(r'^lab-services/$',views.lab_services, name='show_lab'),
    url(r'^lab-reviews/$',views.lab_reviews, name='lab_reviews'),
    url(r'^lab-endorse/$',views.lab_endorse, name='lab_endorse'),
    url(r'^show-your-lab/$',views.show_your_lab, name='show_your_lab'),    
    url(r'^list-your-lab/$',views.list_your_lab,name='list_your_lab'),
    url(r'^lab-profile-page/$',views.lab_profile_page,name='lab_profile_page'),    
    url(r'^edit-provider-profile/$',views.edit_lab_profile,name='edit_lab_profile'),
    # url(r'^edit-provider-services/(?P<lab_service_id>[A-Za-z0-9\w@%._-]+)/$',views.edit_lab_services,name='edit_lab_services'),
    url(r'^provider/lab-service/del/(?P<lab_service_id>[A-Za-z0-9\w@%._-]+)/$',views.del_lab_service,name='del_lab_service'),
    url(r'^provider/provider-service/edit/(?P<lab_service_id>[A-Za-z0-9\w@%._-]+)/$',views.edit_provider_service,name='edit_provider_service'),
    url(r'^lab-photos/$',views.upload_labphotos,name='upload_labphotos'),
    url(r'^upload-pic/$',views.upload_pic,name='upload_pic'),    
    url(r'^upload/profile-pic/$', views.upload_profile_pic,name='upload_profile_pic'),
    url(r'^login1/$',views.image_upload, name='login1'),
    url(r'^lab_list_all/$',views.lab_list_all, name='lab_list_all'),
    url(r'^autocomplete/$', views.searching_labs,name='autocomplete'),
    url(r'^search/$', views.search_result,name='search_result'),
    url(r'^search_keywords/$', views.search_keywords,name='search_keywords'),
    url(r'^searching/$', views.dynamic_searching,name='dynamic_searching'),
    url(r'^demo_publications/$', views. demo_publications,name=' demo_publications'),   
    url(r'^dashboard/$', views.dashboard,name='dashboard'),
    url(r'^search_filters/$', views.search_filters,name='search_filters'),
    url(r'^store-font/(?P<store_id>[0-9]+)/$', views.store_front,name='store_front'),    
    url(r'^parent-services$', views.add_parentservices,name='add_parentservices'),  
    url(r'^book$', views.book_detail,name='book_detail'),  
    url(r'^sample$', views.sample,name='sample'),
    
    url(r'^provider/$', views.labdashboard,name='labdashboard'),
    url(r'^provider/profile/$', views.new_lab_profile,name='new_lab_profile'),
    url(r'^provider/quotes/$', views.new_lab_quotes,name='new_lab_quotes'),
    url(r'^provider/messages/$', views.new_lab_messages,name='new_lab_messages'),
    url(r'^provider/desc/(?P<id>[0-9]+)$', views.view_quote,name='view_quote'),
    url(r'^provider-quote/(?P<qut_id>[0-9]+)/$', views.lab_send_quote,name='lab_send_quote'),
    url(r'^provider/orders/$', views.provider_orders,name='provider_orders'),
    url(r'^provider/order/(?P<ordr_id>[0-9]+)$', views.privider_order_desc,name='provider_order_desc'),
    
    url(r'^buyer/$',views.researcher_profile_page,name='researcher_profile_page'),    
    url(r'^buyer/quotes/$', views.new_res_quotes,name='new_res_quotes'),
    url(r'^buyer/desc/(?P<id>[0-9]+)$', views.res_view_quote,name='res_view_quote'),
    
    url(r'^buyer/edit/basics/$',views.edit_researcher_profile,name='edit_researcher_profile'),
    url(r'^buyer/edit/password/$',views.edit_researcher_password,name='edit_researcher_password'),
    url(r'^buyer/edit/education$',views.researcher_education,name='researcher_education'),
    url(r'^buyer/edit/education/add$',views.add_degree,name='add_degree'),
    url(r'^buyer/edit/education/edit/(?P<degree_id>[0-9]+)/$', views.edit_add_degree,name='edit_add_degree'),
    url(r'^buyer/edit/education/delete/(?P<degree_id>[0-9]+)/$', views.delete_degree,name='delete_degree'),
    url(r'^buyer/edit/publications/$', views.publications,name='add_publications'),
    url(r'^buyer/edit/publications/add$', views.add_publications,name='adding_pub'),
    url(r'^buyer/edit/publications/search$', views.search_publications,name='search_publications'),    
    url(r'^buyer/edit/publications/add/(?P<degree_id>[0-9]+)/$', views.store_publications,name='store_publications'),
    url(r'^buyer/edit/employment/$', views.researcher_employment,name='researcher_employment'),
    url(r'^buyer/edit/employment/add$', views.researcher_add_employment,name='researcher_add_employment'),
    url(r'^buyer/edit/employment/add/(?P<emp_id>[0-9]+)/$', views.edit_add_employment,name='edit_add_employment'),
    url(r'^buyer/edit/employment/delete/(?P<emp_id>[0-9]+)/$', views.delete_employment,name='delete_employment'),
    url(r'^buyer/edit/publications/delete/(?P<emp_id>[0-9]+)/$', views.delete_publications,name='delete_publications'),
    url(r'^buyer/orders/$', views.buyer_orders,name='buyer_orders'),
    url(r'^buyer/order/(?P<ordr_id>[0-9]+)$', views.buyer_order_desc,name='buyer_order_desc'),

    url(r'^send-quote/(?P<serv_id>[0-9]+)/(?P<lab_id>[0-9]+)/$', views.send_quote,name='send_quote'),   
    url(r'^multi-quote/(?P<serv_id>[0-9]+)/$', views.multiquote,name='multiquote'),
    url(r'^multiquote-res/(?P<serv_id>[0-9]+)/$', views.Multiquote_researcher,name='Multiquote_researcher'),    
    url(r'^quote-filter/$', views.quote_status_filter,name='quote_status_filter'),
    
    url(r'^send-quote/thanks/$', views.send_quote_thanks,name='send_quote_thanks'),
    url(r'^service-filters/$', views.service_filters,name='service_filters'),
    url(r'^breadcroomb/$', views.breadcroomb,name='breadcroomb'),

    url(r'^messages/$', views.allmessages, name='allmessages'),
    url(r'^buyer/messages/compose/$', views.compose, name='messages_compose'),
    url(r'^buyer/messages/inbox/$', views.inbox, name='messages_inbox'),
    url(r'^buyer/messages/sent/$', views.outbox, name='messages_outbox'),
    url(r'^buyer/messages/view/(?P<msg_id>[0-9]+)/$', views.buyer_msg_view, name='messages_view'),
    url(r'^buyer/messages/reply/(?P<msg_id>[0-9]+)/$', views.reply, name='messages_reply'),
    url(r'^buyer/messages/trash/$', views.trash, name='messages_trash'),
    url(r'^buyer/messages/trash-box/$', views.trash_messages, name='trash_messages'),
    url(r'^buyer/messages/trash-inbox/$', views.trash_move_inbox, name='trash_move_inbox'),
    url(r'^buyer/messages/trash-delete/$', views.trash_delete, name='trash_delete'),

    url(r'^compose/$', views.messages_compose, name='messages1_compose'),
    url(r'^provider-compose/$', views.provider_messages_compose, name='provider_messages_compose'),

    url(r'^provider/messages/compose/$', views.provider_compose, name='provider_messages_compose'),
    url(r'^provider/messages/inbox/$', views.provider_inbox, name='provider_messages_inbox'),
    url(r'^provider/messages/sent/$', views.provider_outbox, name='provider_messages_outbox'),
    url(r'^provider/messages/view/(?P<msg_id>[0-9]+)/$', views.provider_msg_view, name='provider_msg_view'),
    url(r'^provider/messages/reply/(?P<msg_id>[0-9]+)/$', views.provider_reply, name='provider_messages_reply'),
    url(r'^provider/messages/trash/$', views.provider_trash, name='provider_messages_trash'),
    url(r'^provider/messages/inbox-trash/$', views.move_inbox_trash_provider, name='move_inbox_trash_provider'),
    url(r'^provider/messages/trash-inbox/$', views.trash_move_inbox_provider, name='trash_move_inbox_provider'),
    url(r'^provider/messages/trash-delete/$', views.trash_delete_provider, name='trash_delete_provider'),
    url(r'^provider/messages/sent-trash/$', views.sent_box_provider, name='sent_box_provider'),

    
    url(r'^sort-by-value/$', views.sort_by_value,name='sort_by_value'),    
    url(r'^quote-accept/(?P<qut_id>[0-9]+)/$', views.Quote_accept,name='Quote_accept'),
     url(r'^buyer/quote-reject/(?P<qut_id>[0-9]+)/$', views.Quote_reject,name='Quote_reject'),
    url(r'^testing/$', views.testing, name='testing'),
    url(r'^lab-search-filters/$', views.lab_serch_filters, name='lab_serch_filters'),
    url(r'^proceed-payment/$', views.quote_payment_form, name='quote_payment_form'),
    url(r'^buyer/quote-accept/creditcard/(?P<qut_id>[0-9]+)/$', views.buyer_quote_accept_creditcard, name='buyer_quote_accept_creditcard'),
    url(r'^buyer/payment-type/(?P<qut_id>[0-9]+)/$', views.select_payment_type, name='select_payment_type'),
    url(r'^buyer/quote-accept/wiretransfer/(?P<qut_id>[0-9]+)/$', views.wiretransfer_payment, name='wiretransfer_payment'),
    url(r'^buyer/workroom/(?P<ordr_id>[0-9]+)/$', views.workroom_allocation,name='workroom_allocation'),    
    url(r'^provider/workroom/(?P<ordr_id>[0-9]+)/$', views.provider_workroom,name='provider_workroom'),    


    url(r'^edit/$', views.admin_edit_static, name='admin_edit_static'),
    url(r'^edit1/$', views.admin_edit_staticdata_display,name='admin_edit_staticdata_display'),
    url(r'^staticpage/$', views.admin_staticdata, name='admin_staticdata'),
    url(r'^about_static/$', views.about_static, name='about_static'),

    url(r'^edit_consult/$', views.consulting_edit, name='consulting_edit'),
    url(r'^consult_static/$', views.consulting_static, name='consulting_static'),

    url(r'^projects_edit/$', views.projects_edit, name='projects_edit'),

biomarketx/templates/breadcrumb.html
  <li><a href="/services/Bioimaging/">Services</a></li>
  <li class="active">{{breadcrumb_value}}</li>

biomarketx/templates/labphotos.html
{% extends "./base.html" %}

{% load i18n %}

{% load widget_tweaks %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
            <form action="{% url upload_pic %}" method="post" enctype="multipart/form-data">{% csrf_token %}
                <p>
                    <input id="id_image" type="file" class="" name="image">
                </p>
                <input type="submit" value="Submit" />
            </form>
{% endblock %}

biomarketx/templates/new_about.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load aloha_editor %}

{% block content %}
			<div role="main" class="main">
				
				
				<div class="container">
					<div class="row mt-xl">
						<div class="counters-text-dark">
{% if user.is_authenticated and user.is_superuser %}
<div class="form-group" id="click_id">
											<div class="col-md-8" >
												<a href="{% url 'bioapp:admin_edit_static' %}"><input type="submit" class="btn btn-primary" id="inputDefault" name="submit" value="Edit" style="margin-left: 1117px;width: 112px;margin-top: 21px"></a>
											</div>
										</div>
<!-- 
<div class="form-group">
											<div class="col-md-8" >
												<a href="{% url 'bioapp:admin_edit_staticdata_display' %}"><input type="submit" class="btn btn-primary" id="inputDefault" name="submit" value="Display" style="margin-left: 1117px;width: 112px;margin-top: 21px"></a>
											</div>
										</div> -->
<!-- <div class="form-group" >
											<div class="col-md-8" >
												<a href=" "><input type="submit" class="btn btn-primary" id="inputDefault" name="submit" value="static" style="margin-left: 1117px;width: 112px;margin-top: 21px"></a>
											</div>
										</div>

 -->

{% else %}
{% endif %}





<div id="static_about">

{% if information %}

	{{information|safe}}


{% else %}


			<h1>What we do</h1>
						<div class="clr">&nbsp;</div>
						<div class="col-md-6"><img src="{% static 'new_design/img/what-we-do.png' %}" class="thumbnail" /></div>
						<div class="col-md-6"><p>BioMarketX provides scientific collaborative capabilities aimed at empowering and advancing drug discovery and development.  BioMarketX addresses the growing demand for new partnerships due to the critical mass of specialized expertise and resources, by harnessing the true interdisciplinary nature that can not only solve highly complex challenges of drug discovery and development, but also ensure that scientific breakthroughs are exploited to benefit patients and society.</p>
						</div>
						<div class="clr"></div>
						<div class="col-md-12"><p>BioMarketX also facilitates identification of potential partnerships to initiate strategic relationships to drive clinical research forward.  In addition, through News, BioMarketX provides the latest discoveries and technologies to keep you well-informed.</p>
						</div>




<section class="section section-default">
					<div class="container">
						<div class="srvcs-blk">
						<div class="row">
							<div class="col-md-12 col-sm-12">
								<div data-appear-animation-delay="600" data-appear-animation="fadeInUp" class="counter appear-animation fadeInUp appear-animation-visible" style="animation-delay: 600ms;">
								<h1>Our Mission</h1>
								<div class="clr">&nbsp;</div>	
								<div class="col-md-7"><p>BioMarketX provides scientific collaborative capabilities aimed at empowering and advancing drug discovery and development.  BioMarketX addresses the growing demand for new partnerships due to the critical mass of specialized expertise and resources, by harnessing the true interdisciplinary nature that can not only solve highly complex challenges of drug discovery and development, but also ensure that scientific breakthroughs are exploited to benefit patients and society.</p>
								</div>	
								<div class="col-md-5"><img src="{% static 'new_design/img/our-mission.jpg' %}" class="thumbnail" style="margin-top:15px;" /></div>		
								<div class="clr">&nbsp;</div>
								<div class="col-md-12"><p>BioMarketX also facilitates identification of potential partnerships to initiate strategic relationships to drive clinical research forward.  In addition, through News, BioMarketX provides the latest discoveries and technologies to keep you well-informed.</p>	
								</div>	
								</div>						
						</div>
						</div>
					</div>
				</section>





				<div class="container">

					<div class="row mt-xl">
						<div class="counters-text-dark">
						<h1>How we create value</h1>
						<div class="clr">&nbsp;</div>
						<div class="col-md-2"><img src="{% static 'new_design/img/solutions.jpg'%}" class="thumbnail" /></div>
						<div class="col-md-10"><p>Our success depends on our ability to accelerate your drug discovery and development studies and stimulate creativity for medical research innovation in a secure and confidential way.</p>
						<p>We put our extensive experience and expertise in drug discovery and development, and our broad system of lab partners to work for you to convey new drugs to clinical trials. We join forces with you to develop and manage the most relevant, cost-effective studies for your program.</p>
						
						</div>
						<div class="clr"></div>
						<div class="col-md-12"><p>We have partnered with the most trusted and qualified service providers, each with years of experience and specialized expertise for any drug discovery and development study requirement. Many of these service providers offer unique expertise that cannot be found anywhere else and specialized equipment, often helping you avoid costly mistakes. </p>
						</div>

					</div>
					<div class="clr">&nbsp;</div>
					<div class="col-md-7">
						<h5>Allowing You to Focus on Your Core Expertise</h5>
						<ul>
						<div class="clr">&nbsp;</div>
						<li>Elevates the burden of screening for the best qualified service providers</li>
						<li>Expands capabilities by providing access to specialized labs some of them with unique expertise, and state of the art techniques and equipment</li>
						<li>Provides insights of experts to guide and manage your project</li>
						<li>Substantially saves time and workflow cost</li>
						<li>Provides a private communication with the experts</li>
						<li>Provides a fast, convenient, organized, and affordable way to carry out your drug discovery and development projects</li>
						<li>Provides one highly secure, simple and easy to use portal to handle, and track all projects</li>
						</ul>
					</div>
					<div class="col-md-4 pull-right">
						<div class="row">
							<h5>Bringing the Scientific Community Together</h5>
						<ul>
						<div class="clr">&nbsp;</div>
							<li>Through News, have the latest discoveries at your fingertips</li>

						</ul>
						</div>
						<div class="clr">&nbsp;</div>
						<div class="row">
							<h5>Collaborate with Confidence</h5>
						<ul>
						<div class="clr">&nbsp;</div>
							<li>IP and MTA agreements are available to protect your research</li>
							<li>Non-disclosure agreements guarantee your confidentiality</li>
							<li>Experiment information and reliable results are always secure</li>

						</ul>
						</div>

					</div>

				</div>
				</div>






{% endif %}


					</div>












				</div>
				</div>
								
</div>
				
				
				
			</div>
 
{% endblock %}		

biomarketx/templates/register.html
{% block content %}

<form class="signup" id="signup_form" method="post" action="/register/">
  {% csrf_token %}
  {{ form.as_p }}
Type of Organization/Institution*
<select>
  <option>Company</option>
  <option>University</option>
  <option>Non-profit(Non-academic)</option>
</select>

  <div class="form-actions">
  <button type="submit" class="btn btn-success">Sign Up</button>
  </div>
  <p></p>
</form>

{%endblock%}

biomarketx/templates/reviews.html
{% extends "./base.html" %}

{% load i18n %}



{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
 <div class="container">

          <div class="row">
            <div class="col-md-12">

              <div class="featured-boxes">
                <div class="row">
                  <div class="" style="width:600px;margin:0px auto;height:500px">
                    <div class="featured-box featured-box-primary align-left mt-xlg">
                      <div class="box-content">
                        <h4 class="heading-primary text-uppercase mb-md">Lab-Review</h4>
                        <form action="/lab-reviews/" id="frmSignIn" method="post">
                        {% csrf_token %}
                          <p class="errorlist">{{error_message}}</p>
                          <div class="row">
                            <div class="form-group">
                              <div class="col-md-12">
                                <label>Review</label>
                                {{form.Desc}}
                                {{form.Desc.errors}}
                              </div>
                            </div>
                          </div>
                          <div class="row">
                          <div class="row">
                            
                            <div class="col-md-12">
                              <input type="submit" value="Add-Review" class="btn btn-primary pull-right mb-xl" data-loading-text="Loading...">
                            </div>
                          </div>
                        </form>
                        </div>
                        </form>
                        </div>
                        </div>
                        </div>
                        </div>
                        </div>
                        </div>
                        </div>
                        </div>

</div>

 
 {% endblock %}

biomarketx/templates/signup_success.html
{% extends "base.html" %}

{% load i18n %}



{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
 <div class="background-page">
 <div class="container">

          <div class="row">
            <div class="col-md-12">

              <div class="featured-boxes">
                <div class="row">
                  <div class="" style="width:600px;margin:0px auto;height:500px">
                    <div class="featured-box featured-box-primary align-left mt-xlg">
                      <div class="box-content">
                        <h4 style="text-align:center"class="">Your Registration is now completed.</h4>
                      <div style="padding-top: 17px;">
                      <a href="{% url 'bioapp:login' %}"><button type="button" class="mb-xs mt-xs mr-xs btn btn-primary btn-lg btn-block"><span><i>Sign In to BiomarketX</i></span></button></a></div>
                      </div>
                    </div>
                  </div>
                  </div>
                  </div>
                  </div>
                  </div>
</div>
{% endblock %}

biomarketx/templates/sort-results.html
{% load staticfiles %}
					<!-- <h3>This is about lab page</h3> -->

					{% for lab in all_labs|dictsort:"title" %}
					<div class="lb-rsl-blk">

						<div class="col-md-12">
						<div class="lb-src-rslt lab-prof-rslt">
						<div class="row">
						<div class="col-md-4">
						<a class="rst-title" href="#">{{lab.title}}</a>
						
						<!-- <h6>Anatomical Force Microscopy</h6> -->
						<!-- <h6>{{lab.id}}</h6> -->
						<h6>{{lab.country}} </h6>
						</div>
						<div class="col-md-6"><ul class="portfolio-details lb-cnt-tags">
						<li>
						<ul class="list list-inline list-icons chips">
						<li>20% Reviews</li>
						<li>30 of orders completed</li>
						</ul>
						</li>
						</ul></div>
						<div class="col-md-2">

						<span class="img-thumbnail pull-right">
						<img alt="" class="img-responsive" src="{% static 'new_design/img/comp-1.jpg'%}">
						</span>
						</div>
						</div>
						<div class="row">
						<div class="col-md-12">
						<p class="mt-xlg">{{lab.desc}}</p>
						</div>
						</div>

						<div class="row">
						<div class="clr">&nbsp;</div>
						<div class="col-md-8 pull-right">
						<!-- <div class="col-md-6">
						<input type="checkbox" class="pull-left" name="multiquote" value="{{lab.id}}" />
						<span class="pull-left">&nbsp;&nbsp;Select For Multipul Quotes</span></div> -->
						<div class="portfolio-info stor-frnt col-md-6">
						<a href="/send-quote/{{serviceID}}/{{lab.id}}/" class="btn btn-primary btn-icon pull-right rigtr-btn">Request Quote</a> 
						</div>
						</div>

						</div>

						</div>
						<div class="clr">&nbsp;</div>
						</div>
						</div>
						<form action="/multi-quote/{{serviceID}}/" method="post">
						 {% csrf_token %}
						
						<br>
						<div style=""> 
						<input type="checkbox" class="pull-left" name="multiquote" value="{{lab.id}}" />
						<span>&nbsp;&nbsp;Select For Multipul Quotes</span></div>
						<br>
						{%endfor%}
						<input type="submit" value="Get Quote" class="btn btn-primary btn-icon pull-right rigtr-btn">
						</form>